### PR TITLE
linux-tegra: Update 8822ce driver to 5.12.1.8

### PR DESCRIPTION
**Pull request by acostach**
This change updates the in-tree 8822ce driver
and includes it for all device types present in
this repository.

Default build configuration flags are used,
as present in the original driver source archive.

Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Review by ttomaino — COMMENTED** [review]
Changes look good to me.  Thanks for updating the firmware and enabling 802.11D and 802.11K.

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Pull request merged**
