### PR TITLE
Add L4T 32.7.3 tegra186_tx2_6_dtb file

### PR DESCRIPTION
**Pull request by ttomaino**
This new version of the tegra186_tx2_6.dtb file has been built against L4T 32.7.3.
md5sum e043e5068c98541032cfaaa46b8e47e4

Signed-off-by: Todd Tomaino <toddtomaino@email.com>
Changelog-entry: jetson-dtbs: Update tegra186-tx2-6.dtb

### CODE REVIEW

**Comment by ttomaino** [comment]
@acostach Update .dtb PR.  Not sure how to add you as a reviewer.

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Hi @ttomaino , I replied with a small comment in the ticket, waiting for your confirmation there before I merge this PR.
Thanks

**Comment by acostach** [comment]
Reworded commit message but preserved the same commit contents in https://github.com/balena-os/balena-jetson/pull/572

**Pull request closed without merging**
