### PR TITLE
[WIP] update to 32.3.1

### PR DESCRIPTION
**Pull request by acostach**
This is a work in progress branch. It relies on zeus support from meta-balena and a couple other changes in other repositories to get built fine.

It allows for custom dtb loading for the nano, either from u-boot or from extlinux.conf

Fixes: https://github.com/balena-os/balena-jetson/issues/37

### CODE REVIEW

**Comment by acostach** [comment]
@ZubairLK  Very good stuff in the zeus branch, pretty good results with the nano! There's only one error I'm getting though, from insane.bbclass:

Parsing recipes...ERROR: /yocto/resin-board/build/../layers/meta-balena/meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb: QA Issue: recipe uses DEPENDS_${PN}, should use DEPENDS [pkgvarcheck]
ERROR: /yocto/resin-board/build/../layers/meta-balena/meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb: Fatal QA errors found, failing task.
ERROR: Failed to parse recipe: /yocto/resin-board/build/../layers/meta-balena/meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

Relates to https://github.com/balena-os/meta-balena/issues/1705

**Comment by wremie** [comment]
Great work! I will check with JN30B Rev.4 device somewhere this week. A quick flash of latest JetPack 4.3 in combination with stock Auvidea firmware resulted in kernel crash. Did not look into the issue in detail yet but will come back to the matter.

**Comment by acostach** [comment]
@wremie yes, looks like the upstream machines have changed, hence the build error. I uploaded a couple patches for this, should get past that. Regarding the crashes, don't know if it's due to lack of dtb/firmwares for JP4.3 or something else.

**Comment by wremie** [comment]
@acostach, thanks for the patches. However experiencing some build errors in meta-belena-common concerning the healthdog recipe.

>  ERROR: Task (/home/willem/balena/balena-jetson/build/../layers/meta-balena/meta-balena-common/recipes-core/healthdog/healthdog_0.1.0.bb:do_compile) failed with exit code '1'

[log.do_compile.461](https://github.com/balena-os/balena-jetson/files/4153035/log.do_compile.461.txt)

Will do some testing with JetPack 4.3 and JN30B later today to check what's going on there.

**Comment by JeffJassky** [comment]
Any luck with getting a clean build?

**Comment by wremie** [comment]
@JeffJassky not yet. Although i've found out that Auvidea has not yet released firmware for 32.3.1 and that the current firmware doesn't work with JetPack 4.3....

The last copy of the JN30B has defects so I'm currently not able to test.

**Comment by acostach** [comment]
@wremie Interesting.. can you please try reverting only layers/meta-rust to its' previous revision and  add zeus compatibility to it's layer/conf file?

**Comment by wremie** [comment]
> @wremie Interesting.. can you please try reverting only layers/meta-rust to its' previous revision and add zeus compatibility to it's layer/conf file?

I will receive a new Nano devkit tomorrow so I can try. Next week I will have a Auvidea board again to test things out.

**Comment by wremie** [comment]
@acostach I still didn't find the time to test this WIP. However, wanted to give a headsup now Auvidea released their 32.3.1 BSP [BSP](https://auvidea.eu/firmware/).

**Comment by acostach** [comment]
@floion let's not merge this before the [srd3 PR](https://github.com/balena-os/balena-jetson/pull/47) because for that one there's no 32.3.1 kernel available. I'll rebase this one again after that one is merged.

**Comment by floion** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@balena-ci retest

**Comment by mhodgson** [comment]
@acostach very cool that you included the gasket driver here, but I don't see the changes needed to actually enable it and adjust the kernel params. All the changes here are required to actually make it work: https://github.com/balena-os/balena-jetson/pull/35/commits/5fe7822a48e6bc5720a74437be7bc63bd1c9d3de#diff-4424e95b99ce0fc231765a7ae2463baeR129-R151

**Comment by acostach** [comment]
thanks for the reminder @mhodgson , I've included those now

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@wremie I've merged these changes, so when you get the chance to test it please open a PR to add the specific 32.3.1 dtb you see suitable for the jn30b. Thanks

**Comment by wremie** [comment]
@acostach thanks, I will fork master and update the BSP for JN30B after testing

**Pull request merged**
