### PR TITLE
Add support for CTI Sprocket carrier board

### PR DESCRIPTION
**Pull request by dg10a**
This is a preliminary PR for CTI Sprocket carrier board support, branched from https://github.com/balena-os/balena-jetson/pull/13. The build completes without errors, but I'm running into issues when flashing the image. I'm using the [jetson-flash ](https://github.com/balena-os/jetson-flash) tool. It finishes flashing, but the board fails to boot. I'm guessing it has to be updated for 32.2.

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
@dg10a indeed, you need to add the dtb for 32.2
Otherwise it won't work. Does this PR have that?

**Comment by dg10a** [comment]
Yes, it uses the 32.2 dtb from Connect Tech.

**Comment by acostach** [comment]
@dg10a could you please try to flash the dtb using nvidia BSP flash.sh and then boot the board using the flasher image of your PR? To do this you need to download the 32.2 BSP, unpack it and replace the original tx2 dtbs inside Linux_for_Tegra/kernel/dtb/ with the sproket dtb (ensure it is named the same as the original) and then run the usual flashing process. After dtb is written, boot the board with the flasher image of your PR.

**Comment by floion** [comment]
And this PR needs to be redone. There's some conflicts

**Comment by dg10a** [comment]
This PR now flashes successfully [add_tx2_32_2](https://github.com/balena-os/jetson-flash/tree/add_tx2_32_2) branch in jetson-flash. What needs to be done before this can be merged?

As a side note, 32.2 on the CTI Sprocket doesn't currently have CSI camera support. Can I reopen the Sprocket support PR on [balena-jetson-skx2](https://github.com/balena-os/balena-jetson-skx2)? Alternatively, is it possible to build this repo against 28.2/3?

**Comment by acostach** [comment]
@dg10a Thanks for the contribution! To have support for this board merged it's necessary to open a PR against the master branch of this repository, in which you add each commit per component, following the existing commits as examples. The PR needs to have at least one commit with a Changelog-entry, and each commit needs to have the 'Signed-off-by' line.

Sure, you can re-open a PR in skx2 too! Not sure exactly what building this repo against 28.2/3 means. balena-jetson-skx2 currently has support for L4T 28.3 and this one for 32.2.. So they are incompatible.

**Pull request closed without merging**
