### PR TITLE
Update dtb for photon-nano, photon-xavier-nx to r32.6.1

### PR DESCRIPTION
**Pull request by pgils**
Update device-trees for photon-nano and photon-xavier-nx for l4t r32.6

DTB's are from vendor's BSP packages.

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Hi @pgils and thanks for the PR. We should keep the same device-tree name when updating, some users most likely have their devices configured to use the existing dtb.

**Comment by pgils** [comment]
That makes sense @acostach . I reverted the name change.

**Comment by acostach** [comment]
Thanks @pgils. Could you also update the JN30B dtb please?

**Pull request merged**
