### PR TITLE
workflows: Add build and deploy on release tag workflow

### PR DESCRIPTION
**Pull request by alexgg**
This workflow will launch a Jenkins build and draft deploy job when a new
tag is made.

Changelog-entry: Add build and deploy workflow
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Pull request merged**
