### PR TITLE
tegra186-flash-dry: Update for Aetina N510 boards

### PR DESCRIPTION
**Pull request by compiaffe**
tegra186-flash-dry: Update for Aetina N510 boards

Changelog-entry: tegra186-flash-dry: Update for Aetina N510 board:
L4T 32.4.2
Signed-off-by: Raphael Dürscheid <raphael.duerscheid@aivero.com>

### CODE REVIEW

**Comment by compiaffe** [comment]
@acostach This is obviously not yet signed off by you.

**Comment by acostach** [comment]
Thanks for the PR @compiaffe , you can drop the Author and just add Signed-off-by yourself. I see it's only a DTB update so there's no problem in merging it. 

Please note that the master is now on 32.4.2, I suppose it's a typo in the commit message and the actual version is 32.4.3?

**Comment by compiaffe** [comment]
@acostach all done and yes it was a typo. Thanks :)

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@balena-ci retest

**Review by acostach — APPROVED** [review]

**Comment by acostach** [comment]
Thank you for the updated, got the changes merged in https://github.com/balena-os/balena-jetson/pull/95

**Pull request closed without merging**
