### PR TITLE
layers/meta-balena: Update to v2.107.44

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 2.107.40 to v2.107.44

Changelog-entry: Update meta-balena from v2.107.40 to v2.107.44

### CODE REVIEW

**Comment by alexgg** [comment]
lgtm

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
this just passed - but the github check hasn't been updated yet: https://jenkins.product-os.io/job/leviathan-v2-template/16080/

**Comment by alexgg** [comment]
lgtm

**Pull request merged**
