### PR TITLE
Update CTI Quark and Photon nano

### PR DESCRIPTION
**Pull request by acostach**
Squashes #397 and #398 in a single PR

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by ClintHaerinck** [comment]
Hi @acostach ,

Thanks for the merge. When's the update available at https://www.balena.io/os/ ?

**Comment by acostach** [comment]
Hi @ClintHaerinck , I estimate this or next week, will let you know when they are available

**Comment by acostach** [comment]
@ClintHaerinck the Nano eMMC and Photon Nano are now available at v2.103.2 in production

**Pull request merged**
