### PR TITLE
Add TX2 4gb support

### PR DESCRIPTION
**Pull request by acostach**

### CODE REVIEW

**Comment by smithandrewc** [comment]
Just compiled and tested this pull request.  Using jetson-flash, I'm able to directly flash the emmc with balena-image-flasher-jetson-tx2-4-gb.balenaos-img and the device boots properly.  However, when I flash an sd card with the image, boot up the device (running the above mentioned image) with the flashed sd card in, it detects the sd card, writes to disk and then shuts off (as expected).  However, upon reboot I see

```
...
[0000.969] I> MB2(TBoot-BPMP) done

NOTICE:  BL31: v1.3(release):de895fd9e
NOTICE:  BL31: Built : 12:15:33, Oct 16 2020
ipc-unittest-main: 1519: Welcome to IPC unittest!!!
ipc-unittest-main: 1531: waiting forever
ipc-unittest-srv: 329: Init unittest services!!!
hwkey-agent: 40: hwkey-agent is running!!
hwkey-agent: 182: key_mgnt_processing .......
hwkey-agent: 157: Init hweky-agent services!!
platform_bootstrap_epilog: trusty bootstrap complete
```

It just sits here.  Looks to be something different with this image because flashing with the sd card was confirmed working with #177

**Comment by acostach** [comment]
@smithandrewc can you check if the correct boot0_bindiff is getting applied (https://github.com/balena-os/balena-jetson/pull/180/commits/ff72710e5d6eadc1102370967c7ded02084ff486#diff-400bbe7c0833767b73b6ef25458f8ffb1f82910f2ec9adb9f0bde3e56f3f1d6dR19) and if the correct files are being used: https://github.com/balena-os/balena-jetson/pull/180/commits/ff72710e5d6eadc1102370967c7ded02084ff486#diff-400bbe7c0833767b73b6ef25458f8ffb1f82910f2ec9adb9f0bde3e56f3f1d6dR36 when generating the boot binaries? These two are the only parts that I think could cause this

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
Got confirmation from the maintainer that the TX2 4GB works in the current format.

**Pull request merged**
