### PR TITLE
Update photon-* devices to 32.4.4

### PR DESCRIPTION
**Pull request by pgils**
This updates dtb files for `photon-nano` and `photon-xavier-nx` to l4t r32.4.4. Also switch `photon-nano` and `jn30b-nano` to inherit from `jetson-nano-emmc` since support for that machine was added in b3bff22.

I have added some other minor updates as well, i hope that is okay @acostach

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Review by acostach — APPROVED** [review]
LGTM

**Comment by acostach** [comment]
Thanks @pgils , do the updated images for jn30b and photon work fine with your devices? If you can confirm we can deploy them to production too.

**Comment by pgils** [comment]
Hi @acostach . Local builds for the photon devices work fine for me. I do not have access to `jn30b` devices at the moment so i can not test it. It would be great if you could release `v2.67.3+rev3` for `photon-nano` + `photon-xavier-nx` to staging first so i can test updating.

/cc @dremsol do we have any `jn30b` devices available for testing?

**Comment by acostach** [comment]
Thanks @pgils , the jn30b and photon-nano are already there at 2.67.3+rev2 and the photon xavier-nx should be available in a couple hours or less. rev3 only adds a small fix for the Nano 2GB and has no effect on the other device types.

**Comment by dremsol** [comment]
@pgils we do have some JN30B carrier boards left so testing should be feasible. @acostach the quality of the Auvidea JN30B boards does not meet our standards and we are phasing them out of production. At this moment we only have a couple of them left but soon all of them will be replaced. From memory there are others using this board so maybe there is somebody willing to take over community board support?

**Comment by pgils** [comment]
@acostach the `jn30b` and `photon-nano` are working fine. We installed `v2.56` and updated to `v2.67`. The `photon-xavier-nx` does not pass cboot after updating however, the log is attached. 

I'm not sure if this is related to the issue but i found the `boot0.img` md5sum does not match the one on your comment here:
https://github.com/balena-os/balena-jetson/blob/43d1306252fcf10c7f40c0f50cb38ec3ee01adee/layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra194-nxde-flash-dry_32.4.3.bb#L340
Instead the values for `boot0.img` in the balena images are:
- photon-nx-photon-xavier-nx-2.58.6+rev5: `4b7a6240ed0fd8b0461d215763fb1b65`
- jetson-xavier-nx-devkit-emmc-2.58.6+rev5: `4b7a6240ed0fd8b0461d215763fb1b65` (identical)

Can you confirm this is the correct checksum for the 32.4.3 release?

[photon-nx_cboot.log](https://github.com/balena-os/balena-jetson/files/5903956/photon-nx_cboot.log)

**Comment by EdjeElectronics** [comment]
Hi @pgils , @dremsol , and @acostach , thanks for your help with adding the updated device trees for L4T 32.4.4 on the Photon board. I'm working on a project where we want to use the Raspberry Pi HQ Camera with a Jetson Nano on the Photon board with balenaOS. Connect Tech added a driver for the RasPi HQ Camera on [their latest 32.4.4 BSP release.](https://connecttech.com/ftp/Drivers/L4T-Release-Notes/Jetson-Nano/Nano-32.4.4.pdf) . I tried flashing the latest [CTI Photon Nano BalenaOS 2.67.3+rev2 ](https://www.balena.io/os/#download) onto my Photon Nano and was hoping it would recognize the RasPi Camera. However, it didn't.

Do you know how I can build this release with the RasPi HQ Camera driver? We don't have access to the source code for the drivers, only the .deb packages available from [RidgeRun](https://developer.ridgerun.com/wiki/index.php?title=Raspberry_Pi_HQ_camera_IMX477_Linux_driver_for_Jetson) and [ArduCam](https://www.arducam.com/docs/camera-for-jetson-nano/native-jetson-cameras-imx219-imx477/imx477/) .

**Comment by pgils** [comment]
Hi @EdjeElectronics . The IMX477 sensor driver is included in the r32.4.4 kernel and [enabled by default](https://github.com/OE4T/linux-tegra-4.9/blob/a28ca7b3779d65b032aecf80b58be4d8458a2ded/arch/arm64/configs/tegra_defconfig#L779). The ArduCam module should work out of the box. RidgeRun [provides a patch for the imx477 driver](https://github.com/RidgeRun/NVIDIA-Jetson-IMX477-RPIV3/blob/453e31091dcbc54f57979ad9b5473e962d6bd46a/patches_nano/4.4.1_evm_imx477-v0.1.0.patch#L1906) for the 32.4.4 kernel which might be required. The driver in the CTI BSP is unmodified.

It does however require a different DTB file. CTI ships DTBs which hardcode the type of camera for the CSI interfaces:
```
kernel/dtb/tegra210-nano-cti-NGX003-AR0330-2CAM.dtb
kernel/dtb/tegra210-nano-cti-NGX003-AR0521-2CAM.dtb
kernel/dtb/tegra210-nano-cti-NGX003.dtb
kernel/dtb/tegra210-nano-cti-NGX003-IMX219-2CAM.dtb
kernel/dtb/tegra210-nano-cti-NGX003-IMX327c-2CAM.dtb
kernel/dtb/tegra210-nano-cti-NGX003-IMX477-2CAM.dtb
kernel/dtb/tegra210-nano-cti-NGX003-OV9281-2CAM.dtb
```
Only `tegra210-nano-cti-NGX003.dtb` is included for the `photon-nano` device in balenaOS at the moment. The `tegra210-nano-cti-NGX003-IMX477-2CAM.dtb` should work for you.

Could you try adding that as the default dtb file for `photon-nano` and build with that? Let me know if i can help.

With a recent supervisor (11.14+?) i think the `RESIN_HOST_EXTLINUX_fdt` thing is supposed to work as well. This would make it possible to ship all of these dtb files as part of the [`jetson-dtbs`](https://github.com/balena-os/balena-jetson/blob/master/layers/meta-balena-jetson/recipes-kernel/linux/jetson-dtbs.bb) package and select the one for your camera modules in the 'Device Configuration' section of your device in the balena dashboard. What do you think @acostach ?

**Comment by acostach** [comment]
Thanks @pgils, indeed, for a first quick test it's probably enough to add the tegra210-nano-cti-NGX003-IMX477-2CAM.dtb device tree from https://connecttech.com/product/photon-jetson-nano-ai-camera-platform/ - Jetson Nano 32.4.4 release. This dtb can be placed in the hostOS path '/mnt/sysroot/active/current/boot/' and then set the device tree file name to tegra210-nano-cti-NGX003-IMX477-2CAM.dtb in the dashboard 'Device configuration' tab. The test should be performed using a Photon Nano image 2.67.3+rev2 from the dashboard.

If it doesn't work, @EdjeElectronics can try build the image to also include the lines 1927 to 1967 from https://github.com/RidgeRun/NVIDIA-Jetson-IMX477-RPIV3/blob/453e31091dcbc54f57979ad9b5473e962d6bd46a/patches_nano/4.4.1_evm_imx477-v0.1.0.patch#L1927

**Comment by EdjeElectronics** [comment]
Hey @pgils and @acostach , thanks a bunch for your input! We tried adding the `tegra210-nano-cti-NGX003-IMX477-2CAM.dtb` file to the hostOS at `/mnt/sysroot/active/current/boot/`, and this allowed the container to at least recognize the RasPi HQ camera as /dev/video0. However, when we try to run the camera using a GStreamer command, we get errors that appear to be related to the driver. I'm hoping that applying the RidgeRun patch will fix it!

@acostach how can we build the image to also include lines 1927 to 1967 from the [patch](https://github.com/RidgeRun/NVIDIA-Jetson-IMX477-RPIV3/blob/453e31091dcbc54f57979ad9b5473e962d6bd46a/patches_nano/4.4.1_evm_imx477-v0.1.0.patch#L1927)?

In case you're curious, here's the command used to run the camera (taken from the RidgeRun driver page):

```
SENSOR_ID=0 # 0 for CAM0 and 1 for CAM1 ports
FRAMERATE=60 # Framerate can go from 2 to 60 for 1920x1080 mode
gst-launch-1.0 -e nvarguscamerasrc sensor-id=$SENSOR_ID ! "video/x-raw(memory:NVMM),width=1920,height=1080,framerate=$FRAMERATE/1" ! nvv4l2h264enc ! h264parse ! mp4mux ! filesink location=rpi_v3_imx477_cam$SENSOR_ID.mp4
```

and here's the error GStreamer gives us:
```
(Argus) Error FileOperationFailed: Connecting to nvargus-daemon failed: No such file or directory (in src/rpc/socket/client/SocketClientDispatch.cpp, function openSocketConnection(), line 201)
(Argus) Error FileOperationFailed: Cannot create camera provider (in src/rpc/socket/client/SocketClientDispatch.cpp, function createCameraProvider(), line 102)
Error generated. /dvs/git/dirty/git-master_linux/multimedia/nvgstreamer/gst-nvarguscamera/gstnvarguscamerasrc.cpp, execute:551 Failed to create CameraProvider
```

**Comment by acostach** [comment]
@EdjeElectronics for adding the patch: https://github.com/balena-os/balena-jetson/pull/138
For building: https://github.com/balena-os/balena-jetson#build-information , eg: balena-yocto-scripts/build/barys -b build_photon_nano -m photon-nano

**Comment by dremsol** [comment]
Hi @EdjeElectronics , if i remember correctly this requires `nvargus-daemon` to run on hostos which is included in `tegra-libraries` to properly mount CSI camera to container. However, Balena team is working on host extensions feature which should make this possible and is expected to be available at the end of Q1.

**Comment by acostach** [comment]
@dremsol personally haven't used this but I recall there was a NannyBot project which ran that daemon in container, is this something that has become a requirement in newer L4Ts?

https://forums.balena.io/t/nvidia-jetson-nano-csi-camera-from-container/31917/5
https://forums.balena.io/t/building-a-nanny-bot/10052

**Comment by EdjeElectronics** [comment]
We were able to get it working! We just needed to run `nvargus-daemon &` from the command line inside the container to activate the service. Then, the GStreamer pipeline was able to scuessfully run with the Raspberry Pi HQ Camera.

Thanks a bunch @pgils @acostach @dremsol for all your help!

**Comment by acostach** [comment]
Good to hear that @EdjeElectronics , so is the kernel patch still necessary, did you test with it? Or not, and it can be removed?

**Comment by dremsol** [comment]
@acostach it does work but ideally one wants to abstract this away as the daemon is independent of application in order to use CSI. Therefore i mentioned the HostOS extensions such that people can bootstrap their vision applications even faster.

**Comment by EdjeElectronics** [comment]
No, we did not need to apply the kernel patch. We didn't build our own image, we just used the pre-built CTI Photon Nano BalenaOS 2.67.3+rev2 image. We did need to put the `tegra210-nano-cti-NGX003-IMX477-2CAM.dtb` file in the `/mnt/sysroot/active/current/boot/` folder on the host OS.

**Comment by acostach** [comment]
Good, thanks for confirming @EdjeElectronics. The v2.67.3+rev7 image in the dashboard includes the mentioned dtb in the rootfs, so you can set it directly in the configuration page.

**Comment by EdjeElectronics** [comment]
Hey again @pgils, @dremsol, and @acostach! We're trying to use an [Intel 8265.NGWMG WiFi module](https://www.mouser.com/ProductDetail/Intel/8265NGWMG/?qs=j%252B1pi9TdxUaUVpH7jEPzhA%3D%3D) with our Photon on the CTI Photon Nano BalenaOS. The 8265 WiFi module works (i.e. is able to establish a WiFi connection when configured with an SSID and passkey) on the Jetson Nano Developer Kit with the Nvidia Jetson Nano SD-CARD BalenaOS. However, when we use the 8265 module on the Photon, it doesn't work. Do we need to add our own 8265 driver to the CTI Photon Nano release to get this module working?

Thanks in advance for any help or input you have!

**Comment by dremsol** [comment]
Hi @EdjeElectronics , we did test a cellular modem in the past which basically worked out of the box. Anyway, I think we have a WiFi module in house to test as well. However, could take a couple of days because we all work from home as we are in lockdown in The Netherlands but I will make sure @pgils receives the modules.

**Comment by pgils** [comment]
Great @dremsol !

@EdjeElectronics make sure both switches of the M.2 DIP switch are set to **off** (it's located near the orange cap in the middle of the board). See [page 24 in the manual](https://connecttech.com/ftp/pdf/CTIM_NGX002_Manual.pdf) for details.

**Comment by EdjeElectronics** [comment]
Hey guys, thanks for the input. I made sure the M.2 DIP switches were set correctly, and the WiFi module still isn't working. The dmesg log related to the 8265 iwlwifi driver when I use `dmesg | grep iwlwifi`  with is shown below. It's getting a `Failure to load firmware chunk!` error, which seems to indicate there's an issue.

```
root@be8279b:~# dmesg | grep iwlwifi
[    9.045844] iwlwifi 0000:01:00.0: enabling device (0000 -> 0002)
[    9.050994] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-26.ucode failed with error -2
[    9.050999] iwlwifi 0000:01:00.0: Falling back to user helper
[   70.778079] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-25.ucode failed with error -2
[   70.778103] iwlwifi 0000:01:00.0: Falling back to user helper
[   70.800487] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-24.ucode failed with error -2
[   70.800512] iwlwifi 0000:01:00.0: Falling back to user helper
[   70.813310] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-23.ucode failed with error -2
[   70.813336] iwlwifi 0000:01:00.0: Falling back to user helper
[   70.847833] iwlwifi 0000:01:00.0: loaded firmware version 22.391740.0 op_mode iwlmvm
[   70.955113] iwlwifi 0000:01:00.0: Detected Intel(R) Dual Band Wireless AC 8265, REV=0x230
[   70.957583] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[   70.958432] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[   76.153451] iwlwifi 0000:01:00.0: Failed to load firmware chunk!
[   76.159584] iwlwifi 0000:01:00.0: Could not load the [1] uCode section
[   76.191459] iwlwifi 0000:01:00.0: Failed to start INIT ucode: -110
[   76.243629] WARNING: CPU: 1 PID: 8667 at /yocto/resin-board/build/tmp/work-shared/photon-nano/kernel-source/drivers/net/wireless/intel/iwlwifi/pcie/trans.c:1858 iwl_trans_pcie_grab_nic_access+0xfc/0x118 [iwlwifi]
[   76.243639] Modules linked in: iwlmvm(+) mac80211 nf_conntrack_ipv6 nf_defrag_ipv6 ip6t_REJECT nf_reject_ipv6 ip6table_filter xt_state ipt_REJECT nf_reject_ipv4 ip6_tables ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink br_netfilter xt_owner bnep btusb btrtl btbcm btintel leds_tlc591xx iwlwifi spidev cfg80211 nvgpu
[   76.244019] PC is at iwl_trans_pcie_grab_nic_access+0xfc/0x118 [iwlwifi]
[   76.244153] LR is at iwl_trans_pcie_grab_nic_access+0xfc/0x118 [iwlwifi]
[   76.244687] [<ffffff800129ed84>] iwl_trans_pcie_grab_nic_access+0xfc/0x118 [iwlwifi]
[   76.244818] [<ffffff800128f7e0>] iwl_write_prph+0x48/0xa8 [iwlwifi]
[   76.244951] [<ffffff800129ae44>] iwl_pcie_tx_stop+0x4c/0x1a8 [iwlwifi]
[   76.245083] [<ffffff80012a0ae4>] _iwl_trans_pcie_stop_device.isra.0.part.0+0x24c/0x2e0 [iwlwifi]
[   76.245214] [<ffffff80012a0bbc>] iwl_trans_pcie_stop_device+0x44/0x60 [iwlwifi]
[   76.245672] [<ffffff800129100c>] _iwl_op_mode_start.isra.0+0x54/0xb0 [iwlwifi]
[   76.245803] [<ffffff80012918c4>] iwl_opmode_register+0x74/0xf8 [iwlwifi]
[   78.044839] iwlwifi 0000:01:00.0: Failed to run INIT ucode: -110
[   78.050879] iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
```

I also tried the Intel 8265 module with a regular Jetson Nano Developer Kit running the [Nvidia Jetson Nano SD-CARD BalenaOS 2.69.1+rev1](https://www.balena.io/os/#download) image. The WiFi module does work in this configuration. Here's the output of `dmesg | grep iwlwifi` for this case.

```
root@d664a68:~# dmesg | grep iwlwifi
[   10.068457] iwlwifi 0000:01:00.0: enabling device (0000 -> 0002)
[   10.075217] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-26.ucode failed with error -2
[   10.075222] iwlwifi 0000:01:00.0: Falling back to user helper
[   70.777078] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-25.ucode failed with error -2
[   70.777103] iwlwifi 0000:01:00.0: Falling back to user helper
[  132.216815] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-24.ucode failed with error -2
[  132.216841] iwlwifi 0000:01:00.0: Falling back to user helper
[  193.654327] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-23.ucode failed with error -2
[  193.654351] iwlwifi 0000:01:00.0: Falling back to user helper
[  255.133351] iwlwifi 0000:01:00.0: loaded firmware version 22.391740.0 op_mode iwlmvm
[  255.342315] iwlwifi 0000:01:00.0: Detected Intel(R) Dual Band Wireless AC 8265, REV=0x230
[  255.344862] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.345711] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.470633] thermal thermal_zone6: Registering thermal zone thermal_zone6 for type iwlwifi
[  255.551411] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.551980] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.670578] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.671016] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.753715] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.754763] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.873546] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  255.873984] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  259.873742] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  259.874521] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  259.992054] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  259.992313] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[  263.670347] WARNING: CPU: 3 PID: 2595 at /yocto/resin-board/build/tmp/work-shared/jetson-nano/kernel-source/drivers/net/wireless/intel/iwlwifi/mvm/rs.c:1212 iwl_mvm_rs_tx_status+0x3f4/0x8b8 [iwlmvm]
[  263.670361] Modules linked in: iwlmvm mac80211 nf_conntrack_ipv6 nf_defrag_ipv6 ip6t_REJECT nf_reject_ipv6 ip6table_filter xt_state ipt_REJECT nf_reject_ipv4 ip6_tables ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink br_netfilter xt_owner bnep iwlwifi btusb btrtl btbcm btintel spidev cfg80211 tegra_wdt_t21x nvgpu
[  263.670693] CPU: 3 PID: 2595 Comm: irq/408-iwlwifi Not tainted 4.9.140-l4t-r32.4 #1
[  263.675587] [<ffffff80012f5598>] iwl_pcie_rx_handle_rb+0x188/0x430 [iwlwifi]
[  263.675778] [<ffffff80012f5928>] iwl_pcie_rx_handle+0xe8/0x328 [iwlwifi]
[  263.675971] [<ffffff80012f690c>] iwl_pcie_irq_handler+0x17c/0x790 [iwlwifi]
root@d664a68:~#
```

Do you have any input on what might be causing the firmware issue with the CTI Photon Nano image?

**Comment by dremsol** [comment]
@pgils managed to get WiFi working with following [module](https://up-shop.org/media/productattach/s/p/spec_of_ep-wfdgf109aboi.pdf). However it required an [patch ](https://forums.developer.nvidia.com/t/airetos-aex-qca9880-nx-wifi-module-on-jetson-nano/74626/19
) which seems to be unrelated to your issue. We will continue debugging with an Intel 8265 module.

**Comment by pgils** [comment]
Hi @EdjeElectronics thanks for the logs. I was able to reproduce the issue and work around it by disabling ASPM as described in [this NVIDIA forums thread](https://forums.developer.nvidia.com/t/intel-8265ngw-pcie-error/115337).

It seems to be a common problem with the nano modules and it is disabled for the TX2 in balena as well:
https://github.com/balena-os/balena-jetson/blob/2ae6a66df401a391154ebb2345393e1d6bfec12b/layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%25.bbappend#L245

The `dmesg` log you posted for the Nano sd-card model isn't looking very healthy near the end either. Is the device fully functional and able to reliably connect to a wifi network?

**Comment by acostach** [comment]
@pgils indeed, on the tx2 it was added to fix a problem with the gasket driver for the coral tpu. If it doesn't conflict with your use-case and fixes connectivity for @EdjeElectronics we can include it for the photon-nano by default too

**Comment by EdjeElectronics** [comment]
Hi @pgils, is there a way I can disable ASPM without building a new image?

You're right, the WiFi adapter doesn't seem to work very well on the Nano SD-CARD image either. It takes about 7 minutes after powerup for the device to come online on balena dashboard when the Intel 8265 is installed, but it only takes about 2 minutes when I use a USB WiFi dongle. So it seems like something is happening to at least slow down the 8265 WiFi module at startup.

**Comment by EdjeElectronics** [comment]
Also @dremsol , you mentioned using a cellular module that worked out of the box. What was the manufacturer and part number for the module? I'm testing with a Quectel EM06-A module (which was recommended by Connect Tech to use with the Photon). It does seem to be recognized by balenaOS (see dmesg log below). However, it isn't establishing an internet connection even when I set it up as described in the [balenaOS networking documentation](https://www.balena.io/docs/reference/OS/network/2.x/#cellular-modem-setup). The module does work with Jetson OS, though.

```
root@be8279b:~# dmesg | grep 1-2.2
[    1.693251] usb 1-2.2: new high-speed USB device number 3 using tegra-xusb
[    1.714551] usb 1-2.2: New USB device found, idVendor=2c7c, idProduct=0306
[    1.714558] usb 1-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.714563] usb 1-2.2: Product: EM06-A
[    1.714568] usb 1-2.2: Manufacturer: Quectel
[    1.714572] usb 1-2.2: SerialNumber: 0123456789ABCDEF
[    9.233992] option 1-2.2:1.0: GSM modem (1-port) converter detected
[    9.235359] usb 1-2.2: GSM modem (1-port) converter now attached to ttyUSB0
[    9.235445] option 1-2.2:1.1: GSM modem (1-port) converter detected
[    9.235622] usb 1-2.2: GSM modem (1-port) converter now attached to ttyUSB1
[    9.235686] option 1-2.2:1.2: GSM modem (1-port) converter detected
[    9.236916] usb 1-2.2: GSM modem (1-port) converter now attached to ttyUSB2
[    9.236998] option 1-2.2:1.3: GSM modem (1-port) converter detected
[    9.237180] usb 1-2.2: GSM modem (1-port) converter now attached to ttyUSB3
[    9.283627] cdc_mbim 1-2.2:1.4: cdc-wdm0: USB WDM device
[    9.284011] cdc_mbim 1-2.2:1.4 wwan0: register 'cdc_mbim' at usb-70090000.xusb-2.2, CDC MBIM, ba:d5:26:be:aa:b5
```

**Comment by dremsol** [comment]
Hi @EdjeElectronics, we've been testing with (Sierra Wireless EM7455)[https://techship.com/products/sierra-wireless-em7455/002/1103780/] ordered at Techship.

**Comment by EdjeElectronics** [comment]
Hey @pgils , just wanted to ping you again: is there any way to disable ASPM without building a whole new balenaOS image?

@dremsol thanks for the heads up. I was able to get the Quectel EM06-A module working with the CTI Photon image. I just needed to remove the "username=" and "password=" lines from the cellular configuration file example provided on the [balenaOS Networking](https://www.balena.io/docs/reference/OS/network/2.x/#cellular-modem-setup) page.

**Comment by acostach** [comment]
@EdjeElectronics if it's just for the purpose of local testing, you can add it to /mnt/sysroot/active/current/boot/extlinux/extlinux.conf 
This setting won't persist trough OS updates, so if you confirm it to work fine we can include it by default in the dashboard image.

**Comment by EdjeElectronics** [comment]
Thanks @acostach ! Can you give some specific instructions how how to add it to the extlinux.conf file? Here's the file I currently have:

```
DEFAULT primary
TIMEOUT 10
MENU TITLE Boot Options
LABEL primary
      MENU LABEL primary boot/Image
      LINUX /boot/Image
      FDT default
      APPEND ${cbootargs} ${resin_kernel_root} ro rootwait ${os_cmdline} sdhci_tegra.en_boot_part_access=1
```

Where should I add the ASPM line? From the [link](https://github.com/balena-os/balena-jetson/blob/2ae6a66df401a391154ebb2345393e1d6bfec12b/layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%25.bbappend#L245) that @gpils shared, it looks like I need to add something like this:
`KERNEL_ROOTSPEC_jetson-tx2 = " \${resin_kernel_root} ro rootwait gasket.dma_bit_mask=32 pcie_aspm=off"` . Does that need to be changed at all?

**Comment by EdjeElectronics** [comment]
It works now! I disabled ASPM by changing my /mnt/sysroot/active/current/boot/extlinux/extlinux.conf to this:

```
DEFAULT primary
TIMEOUT 10
MENU TITLE Boot Options
LABEL primary
      MENU LABEL primary boot/Image
      LINUX /boot/Image
      FDT default
      APPEND ${cbootargs} ${resin_kernel_root} ro rootwait ${os_cmdline} sdhci_tegra.en_boot_part_access=1 pcie_aspm=off
```

My Intel 8265 WiFi module is able to establish an internet connection now, and I'm able to see the device online through the balena dashboard.

Thanks for all your help, guys!

**Comment by dtischler** [comment]
Been following along, awesome!

**Comment by pgils** [comment]
Great to hear you got it to work @EdjeElectronics !

I've opened #146 for a permanent fix and balena-os/meta-balena#2121 to address the long wait on powerup as well.

**Comment by acostach** [comment]
Thanks for the PR @pgils, so @EdjeElectronics the new image 2.69.1+rev4 for the Photon Nano includes the change by default.

**Pull request merged**
