### PR TITLE
linux-tegra: Update tegra186-tx2-6 dtb

### PR DESCRIPTION
**Pull request by acostach**
This PR updates the tegra186-tx2-6.dtb
for a custom TX2 based device.

This version of the DTB is provided in
https://jel.ly.fish/302289d9-fe59-4898-b513-ce84c530f6b7
(internal reference)

Changelog-entry: linux-tegra: Update tegra186-tx2-6 dtb
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@AeroNotix does this dtb work as expected if specified as custom DTB in the dashboard?

Or it works only if flashed to the hardware partitions bootloader-dtb / kernel-dtb ?

**Comment by AeroNotix** [comment]
I've tried a tonne of variations over the last few days, I'm pretty sure I tried writing this DTB into /boot/ and specifying it. We'll chat more tomorrow about our future plans but I ceased attempting to OTA update - will give it a go again to fully confirm the behaviour when OTA'd to 2.69.1+ with this DTB specified in the device-configuration.

**Comment by acostach** [comment]
@AeroNotix the new dtb should overwrite the one in /mnt/sysroot/active/current/boot/ and if the dtb name 'tegra186-tx2-6.dtb' is specified in the dashboard, and the image is of type 'development', you should also see in the u-boot logs that this dtb is being loaded.

**Comment by acostach** [comment]
The dev image only prints u-boot logs and confirms if the dtb specified in the dashboard is actually loaded, has no role other than that.

**Comment by AeroNotix** [comment]
Alright - I'm dealing with https://github.com/balena-os/jetson-flash/issues/39 today but when finished dealing with this and allowed other people working on this to be unblocked, I'll get back to the OTA upgrade path.

**Comment by AeroNotix** [comment]
Appreciate the help immensely @acostach !

**Comment by acostach** [comment]
you're welcome @AeroNotix , btw https://github.com/balena-os/jetson-flash/issues/39 should now work by default in v0.5.7

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
