### PR TITLE
Use udev by-state symlinks

### PR DESCRIPTION
**Pull request by alexgg**
This changes are required for the v2.49.0+rev1  release after:
https://github.com/balena-os/meta-balena/pull/1840

has been merged into meta-balena.

### CODE REVIEW

**Comment by acostach** [comment]
@alexgg guess it needs one 'Changelog-entry' in one of the commits for the versionist.

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
> @alexgg guess it needs one 'Changelog-entry' in one of the commits for the versionist.
Done

**Comment by acostach** [comment]
@alexgg I checked this PR with meta-balena development branch at commit https://github.com/balena-os/meta-balena/commit/5bc74e1d7e7e21c6aa96f3d121a3939b06af2db1 on a TX2, and the behavior I see is the board rebooting continuously in the initramfs:

```
[   12.901559] EXT4-fs (mmcblk0p25): couldn't mount aities
[   12.927232] EXT4-fs (mmcblk0p25): mounted filesystem with ordered data mode. Opts: (null)
[   12.983229] EXT4-fs (mmcblk0p27): mounted filesystem with ordered data mode. Opts: (null)
[   13.342431] EXT4-fs (mmcblk0p25): re-mounted. Opts: (null)
INFO[0000] Pruned 1 unused graph dd not move mountpoint: /sys no such file oruntpoint: /run no such file or directory
2t: /etc/machine-id no such file or directory
2020/04/24 08:29:34 error while pivoting
```

Sorry the logs are a bit scrambled due to an MCU via which the uart is passed trough on this TX2 carrier board, but maybe they provide a hint on what might be happening.

Also, when booting the flasher I don't see this behavior, it only happens when loading from emmc.

**Comment by alexgg** [comment]
thanks @acostach I'll check

**Comment by alexgg** [comment]
@acostach the failure is caused by a latter commit in development, unrelated to this commit.  The last working commit in meta-balena is 26f67abe90fa

**Comment by acostach** [comment]
thanks @alexgg , I replied in the original fd thread, was saying the last meta-balena dev commit causes failure on the pi4 too

**Comment by acostach** [comment]
@balena-ci retest this please

**Pull request merged**
