### PR TITLE
Dv 820 add configuration 6 tx2 config kernel49

### PR DESCRIPTION
**Pull request by AeroNotix**

### CODE REVIEW

**Comment by floion** [comment]
Hi @AeroNotix as you are aware, we won't be adding new machine configs for config option changes. So we will be using the supervisor to change the odm data through the supervisor as you saw in https://github.com/balena-io/balena-supervisor/issues/1206 and https://github.com/balena-io/balena-supervisor/issues/1207
So this PR needs to be modified and remove that part from it. We'll take a look at the backport-iwlwifi recipe and see how to better add it to the rootfs (either add it here in this repo or instead add it in meta-balena)

**Comment by AeroNotix** [comment]
@floion what's the timeline of the two tickets you linked?

**Comment by floion** [comment]
@CameronDiver @richbayliss any hint on timelines for https://github.com/balena-io/balena-supervisor/issues/1206 and https://github.com/balena-io/balena-supervisor/issues/1207 ?

**Comment by AeroNotix** [comment]
@CameronDiver @richbayliss  9 days ago a colleague and myself asked you this, https://github.com/balena-os/balena-jetson/pull/49#issuecomment-594182086

**Comment by CameronDiver** [comment]
No timeline yet, we have a few pressing issues that are being dealt with first.

**Comment by AeroNotix** [comment]
@CameronDiver thanks for the update. Appreciate it!

**Pull request closed without merging**
