### PR TITLE
jetson-dtbs: Install device tree JN30B with changed cam config

### PR DESCRIPTION
**Pull request by ClintHaerinck**
Device tree added for Auvidea JN30B board with the pixel format of
cam 1 flipped. The pixel bayer pattern is changed from RGGB to BGGR.

Changelog-entry: Added device tree for JN30B with cam1 pixel format flipped

Signed-off-by: Clint Haerinck <clint.haerinck@citymesh.com>

### CODE REVIEW

**Comment by acostach** [comment]
Thanks for the PR @ClintHaerinck , I've reformatted the commit message in https://github.com/balena-os/balena-jetson/pull/203 for automated versioning checks to pass. Is this a L4T 32.5.1 based or compatible dtb for the jn30b? If so, I'll merge it and release the image in the cloud.

**Comment by ClintHaerinck** [comment]
Thanks for the reformatting. It's based on the JN30B dtb of balenaOS 2.67.3+rev2. I was wondering if there's a way to still use it with L4T version R32.4.4?

**Comment by acostach** [comment]
@ClintHaerinck , we just moved to L4T 32.5.1 so unfortunately there won't be any new images released on 32.4.4. You can build the yocto image locally if you want to use a particular version/L4T.

**Comment by ClintHaerinck** [comment]
Ok, I will port the changes to L4T 32.5.1.
I also have other changes to be done in device tree but I didn't manage to build a working DTB from source. Can you please verify my working method? I'm not sure if I'm missing something or if their are mistakes in my DTS changes.
What I do:
* A full Yocto build
* Source the build directory if not already sourced
* `bitbake linux-tegra -c devshell`
Inside the devshell I apply the patches and make, make dtbs to generate the device tree blobs. Then the generated dtb I copy to /mnt/sysroot/active/current/boot and change the desired dtb in balenaCloud.

Is this the way to go?

**Comment by acostach** [comment]
@ClintHaerinck modifying the existing device tree sources in from the yocto setup means changing the Nano devkit dtb, which is probably not what you want because it doesn't include the Auvidea changes for dts.

The dtb for the JN30B community supported board is included in the image build as-is - pre-compiled. This means it's downloaded from the Auvidea's website and placed in the sources directory. To modify it, you can either decompile, edit and recompile with dtc, or, if Auvidea provides the kernel sources, edit the dts, build the Auvidea kernel and PR the resulting dtb.

**Comment by ClintHaerinck** [comment]
Auvidea provides the sources, the patches I'm applying in my last step are the Auvidea dts changes with some modifications. Ok so my working method seems fine then. I will check the changes again. Thanks

**Pull request closed without merging**
