### PR TITLE
Add AAEON BOXER-8221AI device type

### PR DESCRIPTION
**Pull request by pgils**
Add device type for AAEON BOXER-8221AI.

I have added the common `boxer-nano` MACHINEOVERRIDE to allow easy addition of other devices from the same series: [AAEON NVIDIA AI](https://www.aaeon.com/en/c/aaeon-nvidia-ai-solutions).

### CODE REVIEW

**Comment by acostach** [comment]
Hi @pgils and thanks for the PR. The Nanos support custom dtb loading so I'm wondering if it couldn't be initially booted with the Nano eMMC image and just switch to the Aaeon dtb once it's up and running.

**Comment by pgils** [comment]
> Hi @pgils and thanks for the PR. The Nanos support custom dtb loading so I'm wondering if it couldn't be initially booted with the Nano eMMC image and just switch to the Aaeon dtb once it's up and running.

Hi @acostach coul you point me to some documentation on this perhaps? I'm unable to get this to work. What i tried:

**Comment by acostach** [comment]
Hi @pgils can you try upload the file to /mnt/sysroot/active/current/boot/ , near the rest of the existing dtbs and and then set RESIN_HOST_EXTLINUX_fdt in the dashboard?

**Comment by pgils** [comment]
Thanks @acostach, it works now.

If i understand correctly, the dtb file would need to be added to the `jetson-dtbs` package to make this persistent, corrent?
Are there plans to support uploading `dtb` files in the dashboard?

**Comment by acostach** [comment]
Closing this PR as per the above confirmation

**Pull request closed without merging**
