### PR TITLE
Add TX2 Machine with M.2 PCIe Enabled

### PR DESCRIPTION
**Pull request by mhodgson**
Same modifications that were applied to the balena-jetson-skx2 repo. Built and verified on TX2 dev board.

### CODE REVIEW

**Comment by acostach** [comment]
@mhodgson can you please check if you can switch between configurations in the hostOS or in the container, on both 28.3 and 32.2 (I assume you built your own image for this), using this small tool I put together here: https://www.dropbox.com/s/0olwqj2pjxy9j9q/odmtool?dl=0

I included configurations 1,2 and 3, and after switching the configuration you need to reboot the board for the changes to take effect. You should be able to check current value before and after writing it.

Also, please note that there is a possibility for the board to not boot after switching the configuration. This did not happen on my side, neither with 28.3 or 32.2, but I'm letting you know so you can save any important work you had on it.

**Comment by mhodgson** [comment]
@acostach ah, bad timing. Just got home for the weekend (no devices here). I will try this on Monday. What exactly is that tool, a binary? Are there arguments I need to pass to it?

**Comment by acostach** [comment]
@mhodgson yes, it's a statically linked binary I put together for switching the odmdata on any tx2 running balenaOS. It should work even if you are using your custom builds. If you could confirm or infirm if it works for both 28.3 and 32.2 for detecting the m2 coral device, we can look further into ways of not having a need for a new special machine for the odmdata change and just include the coral drivers in the base tx2 release. If you run it with no args, it will print the expected usage and let you choose from the currently implemented configurations for odmdata, 1 to 3. You will need to reboot the board after aplying any configuration change. Please let me know if it works on your side.

**Comment by mhodgson** [comment]
@acostach I was able to test this on the current (L4T 28.3) image and verify that it does appear to enable configuration 1 properly (I can list and see the M.2 PCIe card). 

I'm running into errors building the stock L4T 32.2 image from this repo. Is there an easy place I can download the latest image from master in this repo? I assume Balena is automatically building it somewhere.

**Comment by acostach** [comment]
@mhodgson Thank you for confirming 28.3. For 32.2 you can check with the instruction below. It doesn't include coral drivers but is fine for testing the tool approach:
hostapp-update -r -i acostach/tx2:tx2_32_2_test_hup_bundle

**Comment by mhodgson** [comment]
@acostach success! The tool appears to work in both versions. So, how should we proceed? Perhaps:

1. Remove the new machine that was added in balena-jetson-skx2.
2. Add the gasket driver to the jetson-tx2 default machine.
3. Add your odmtool to the jetson-tx2 default machine?

My only real concern is that here in the 32.x verson of L4T I had to add the pcie_aspm=off kernel argument. Without this, the board will not boot (if the Coral M.2 card is attached). I'm not super familiar with ASPM. Do you think disabling it by default will cause other issues? This was not an issue in 28.x, so either nvidia didn't enable ASPM in that version of the kernel, or something else is going on.

**Comment by mhodgson** [comment]
@acostach looks like L4T 32.2 is released on the dashboard? What do you want to do with this? Should I make a PR that just adds the gasket driver to the `jetson-tx2` machine?

**Comment by acostach** [comment]
@mhodgson yes, we released 2.47 with 32.2 for the TX2 that comes in the standard configuration.

We're currently discussing internally regarding the best way to go forward for m2pcie and other related configurations, also based on the results you had with switching odmdata. Since BSP changes significantly from one l4t release to another and can be incompatible with previous ones, we need to find the best way to keep the overall setup as predictable as possible from a user point of view. I'll get back to you on this when we reached a conclusion.

**Comment by mhodgson** [comment]
@acostach thanks for the quick response. You guys should let people know about the 32.2 release! That's a big deal :) 

Keep me posted on the driver/ODMDATA situation.

**Comment by acostach** [comment]
@mhodgson to keep you updated, we have started working on the feature that will help switching usb3.0/pcie configuration and select custom dtbs from the dashboard. Also, L4T 32.3.1 is in progress in this PR https://github.com/balena-os/balena-jetson/pull/39 . I've included the gasket driver there too.

**Comment by mhodgson** [comment]
@acostach Hope you are well. Any updates on the above items? I see #39 was merged 3 weeks ago but I still don't see it in the UI. And the feature for setting ODMDATA from the UI?

**Comment by acostach** [comment]
Hi @mhodgson , indeed, the device-side part has been merged already, the supervisor part is currently work in progress.

**Comment by acostach** [comment]
Closing this old PR as the latest 32.7.3 dtb has been merged in https://github.com/balena-os/balena-jetson/pull/572

**Pull request closed without merging**
