### PR TITLE
linux-tegra: update CTI Photon TX2 NX IMX477 dtb R32.7.1

### PR DESCRIPTION
**Pull request by ClintHaerinck**
Update CTI Photon TX2 NX IMX477 dtb to L4T R32.7.1
The dtb file is renamed by CTI. Also added dtb with old name to boot
partition for backward compatibility.

Changelog-entry: linux-tegra: Update IMX477 dtb photon-tx2-nx L4T
R32.7.1
Signed-off-by: Clint Haerinck <clint.haerinck@citymesh.com>

### CODE REVIEW

**Comment by acostach** [comment]
Hi @stathismor , any idea why VB fails here?

@ClintHaerinck Thanks for your PR, could you please keep the device-tree names as they were so we don't default to the standard TX2 NX device-tree when updating the OS with the dtb name already set in the dashboard?

**Comment by ClintHaerinck** [comment]
@acostach That's the reason I've installed the dtb at the boot parition with old and new name. Do you have any concern about the method?

**Comment by stathismor** [comment]
@acostach versionist gets confused because of the new line before `R32.7.1` in the `Changelog-entry`. Make that one line and it will be fine.

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Review by acostach — APPROVED** [review]
lgtm

**Pull request merged**
