### PR TITLE
WIP: N510

### PR DESCRIPTION
**Pull request by compiaffe**
**WIP**

Adding Aetina N510 and N310 carrier boards.

### CODE REVIEW

**Comment by compiaffe** [comment]
The N310 .dtb is a beta version. The N510 is still the old and will be replaced once I have a 32.2.1 based one.

**Comment by compiaffe** [comment]
@floion @acostach I'm adding support for the Aetina N310 board, too. 

What do I need to do to get the matching slug: `n310-tx2` into the balena CLI?

**Comment by acostach** [comment]
@compiaffe can you please re-base these changes as some of the PRs were merged already. Thank you

**Comment by floion** [comment]
Hi, can you rebase on top of master please?

**Comment by compiaffe** [comment]
@acostach @floion This is blocked right now as I am waiting on an updated .dtb from the board manufacturer. Will rebase when I pick this up again.

**Comment by acostach** [comment]
All good then @compiaffe , thank you for the update!

**Comment by compiaffe** [comment]
@acostach @floion I've recreated an MR based on master here: https://github.com/balena-os/balena-jetson/pull/53
Closing this MR

**Pull request closed without merging**
