### PR TITLE
Update dtb file for jn30b-nano 32.6.1

### PR DESCRIPTION
**Pull request by pgils**
Update DTB file for Auvideo jn30b nano.

DTB file taken from vendor's BSP v5.0.

### CODE REVIEW

**Comment by pgils** [comment]
I was unable to test this because i do not have access to any JN30B devices.

**Comment by acostach** [comment]
Thanks @pgils , it will need to be renamed, for the JN30B it is:
```
u-boot:
TEGRA_BOARD_FDT_FILE:jn30b-nano="tegra210-p3448-0002-p3449-0000-b00-jn30b.dtb"
...
kernel:
SRC_URI:append:jn30b-nano = " \
    file://tegra210-p3448-0002-p3449-0000-b00-jn30b.dtb \
"
```

**Comment by pgils** [comment]
> Thanks @pgils , it will need to be renamed, for the JN30B it is:
> 
> ```
> u-boot:
> TEGRA_BOARD_FDT_FILE:jn30b-nano="tegra210-p3448-0002-p3449-0000-b00-jn30b.dtb"
> ...
> kernel:
> SRC_URI:append:jn30b-nano = " \
>     file://tegra210-p3448-0002-p3449-0000-b00-jn30b.dtb \
> "
> ```

Sorry about that. Should be fixed now @acostach 

I'm not familiar with the [`*jn30b-cam1-flip.dtb`](https://github.com/balena-os/balena-jetson/blob/master/layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/tegra210-p3448-0002-p3449-0000-b00-jn30b-cam1-flip.dtb) version of the device-tree. Is this a custom patched version @ClintHaerinck ? Or is it available in the Auvidea BSP?

**Comment by ClintHaerinck** [comment]
@pgils Yes it's a custom version. I will also update this one.

**Comment by acostach** [comment]
@resin-jenkins test this please

**Review by acostach — APPROVED** [review]
lgtm

**Pull request merged**
