### PR TITLE
balena-yocto-scripts: Update to v1.21.3

### PR DESCRIPTION
**Pull request by alexgg**
Update balena-yocto-scripts from v1.14.8 to v1.21.3

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.21.3

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
lgtm

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request closed without merging**
