### PR TITLE
WIP: Add support for SPI on GPIOs of Jetson Nano Device

### PR DESCRIPTION
**Pull request by Langhalsdino**
### Adding support for SPI on the GPIO Pins of Jetson Nano Carrier board

By default SPI devices such as `/dev/spidev0.0` is not listed on the Jetson Nano dev board. Therefore some device tree modifications need to be made, as described in a lot of NVIDIA Forum entries, [Balena Forum](https://forums.balena.io/t/jetson-nano-access-to-spi-device/59471/7) and [GitHub repos](https://github.com/rt-net/JetsonNano_DT_SPI).

Therefore, I added a seperate machine that is called `spi-jetson-nano` to this repository. It contains a modified Device Tree that enables the SPI device on the same GPIOs as the raspberry pi.

### Done
-  added .coffee and .svg for `spi-jetson-nano`
- conf/machine: added machine configuration
- .bbappend: SRC_URI and do_deploy_append

### ToDo
- We use a modified .dtb file internally and i still need to clean it up, so it only contains the necessary changes. I will add the file soon. Just need to check a few things before pushing the .dtb file. If some one else is faster building a .dtb similar to this [GitHub project](https://github.com/rt-net/JetsonNano_DT_SPI) feel free to contribute.

I am very new to contributing to this project therefore, please show me what i need to do, in order to merge this PR.

### CODE REVIEW

**Comment by Langhalsdino** [comment]
I am running a fresh build at night and hopefully everything will be okay by tomorrow morning and i did not do any more typos 🙈

**Comment by acostach** [comment]
Hi @Langhalsdino , in https://github.com/balena-os/balena-jetson/issues/37 we'll be tracking support for custom dtb loading from extlinux.conf . This would help avoid the need for a new device type for the same hardware, and should become available after we'll upgrade to L4T 32.3 for the Jetson Nano.

**Comment by Langhalsdino** [comment]
@acostach That sounds great.

Since this still work in progress, SPI is still not working, due to a bug in the tegra gpio drivers in the linux kernel.

The following patch need to be applied to the linux kernel:
```patch
diff a/drivers/gpio/gpio-tegra.c b/drivers/gpio/gpio-tegra.c
--- drivers/gpio/gpio-tegra.c
+++ drivers/gpio/gpio-tegra_new.c
@@ -223,10 +223,18 @@
        return pinctrl_request_gpio(chip->base + offset);
 }

+static void tegra_gpio_disable(struct tegra_gpio_info *tgi, int gpio)
+{
+       tegra_gpio_mask_write(tgi, GPIO_MSK_CNF(tgi, gpio), gpio, 0);
+}
+
 static void tegra_gpio_free(struct gpio_chip *chip, unsigned offset)
 {
+       struct tegra_gpio_info *tgi = gpiochip_get_data(chip);
+
        pinctrl_free_gpio(chip->base + offset);
        tegra_gpio_restore_gpio_state(offset);
+       tegra_gpio_disable(tgi, offset);
 }

 static void tegra_gpio_set(struct gpio_chip *chip, unsigned offset, int value)
```


Somehow i can not get the patch to work, since my file references seem to be wrong. I have no clue how to setup the yocto SDK inside the project, therefore i can only build the patches manually. Do you know whats off @acostach ?

Error:
```bash
9+gitAUTOINC+3dcbed5d27-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-spi-patch-linux-drivers-gpio-tegra.patch
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff a/drivers/gpio/gpio-tegra.c b/drivers/gpio/gpio-tegra.c
|--- drivers/gpio/gpio-tegra.c
|+++ drivers/gpio/gpio-tegra_new.c
--------------------------
No file to patch.  Skipping patch.```

**Comment by floion** [comment]
@Langhalsdino did you get the patch from upstream? If yes, can you paste the link from upstream here please?

**Comment by Langhalsdino** [comment]
@floion I used this patch to fix the drivers within the image provided by Nvidia. And try to manually put it into the project. I will commit my changes, so you get a better understanding about what i mean.

Since it was manually inserted into the project and layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend by appending it to the SRC_URI the path might be off or i did something stupid, since i am not used to yocot

**Comment by Langhalsdino** [comment]
Sorry missed to provide the link 🙈 
https://devtalk.nvidia.com/default/topic/1050427/jetson-nano/enabling-spidev-on-the-jetson-nano-is-hanging-when-flashing/4

**Comment by acostach** [comment]
@Langhalsdino I'll push a PR with the patch today, I'll ping you here with the link to it when it's ready

**Comment by Langhalsdino** [comment]
> @Langhalsdino I'll push a PR with the patch today, I'll ping you here with the link to it when it's ready

Awesome, thank you :) This will help us a lot!

**Comment by Langhalsdino** [comment]
Got it to work by using:
```patch
diff a/kernel-source/drivers/gpio/gpio-tegra.c b/kernel-source/drivers/gpio/gpio-tegra.c
--- kernel-source/drivers/gpio/gpio-tegra.c
+++ kernel-source/drivers/gpio/gpio-tegra_new.c
@@ -223,10 +223,18 @@
        return pinctrl_request_gpio(chip->base + offset);
 }

+static void tegra_gpio_disable(struct tegra_gpio_info *tgi, int gpio)
+{
+       tegra_gpio_mask_write(tgi, GPIO_MSK_CNF(tgi, gpio), gpio, 0);
+}
+
 static void tegra_gpio_free(struct gpio_chip *chip, unsigned offset)
 {
+       struct tegra_gpio_info *tgi = gpiochip_get_data(chip);
+
        pinctrl_free_gpio(chip->base + offset);
        tegra_gpio_restore_gpio_state(offset);
+       tegra_gpio_disable(tgi, offset);
 }

```

**Comment by Langhalsdino** [comment]
Tested it with loopback and the python library spidev

```python3
import spidev
import time

spi = spidev.SpiDev()
spi.open(0, 0)

def BytesToHex(Bytes):
    return ''.join(["0x%02X " % x for x in Bytes]).strip()

try:
    while True:
        resp = spi.xfer2([0x01, 0x02])
        print(BytesToHex(resp))
        time.sleep(1)

except KeyboardInterrupt:
    spi.close()
```

Output:
```
0x00 0x00
0x00 0x00
0x00 0x00
0x00 0x00
0x00 0x00
0x00 0x00
0x00 0x00
```
addin jumper wire on pin 19 and 21
```
0x01 0x02
0x01 0x02
0x01 0x02
0x01 0x02
```

**Comment by Langhalsdino** [comment]
If you want to compile your own `.dtb` , use the following GitHub repository to compile it:
https://github.com/rt-net/JetsonNano_DT_SPI

Since it based on Nvidias intellectual property (Linux 4 Tegra) i am not sure, if i can publish the compiled .dtb here. Any thoughts?

**Comment by acostach** [comment]
@Langhalsdino here's the PR with the kernel patch: https://github.com/balena-os/balena-jetson/pull/40

**Comment by Langhalsdino** [comment]
@acostach Cool thank you.

Just out of curiosity how did you create the patch? I manually patched the file in the shared work-directory in order to get it to work :D

**Comment by Langhalsdino** [comment]
What are the next steps for the PR? Wait for #37 and #40 to be merged and close it afterwards?

**Comment by acostach** [comment]
@Langhalsdino Done by patching the kernel sources that are pulled during the yocto build: <build_dir>/tmp/work/jetson_nano-poky-linux/linux-tegra/4.9+git.../git/

Yes, the plan is for #40 to get merged first. After that you can use your own local builds until [L4T 32.3.1](https://github.com/balena-os/balena-jetson/pull/39) becomes available and allows for custom dtbs without re-flashing the dtb partitions. We try to avoid adding a new device type for the same hardware only due to configuration changes, like in this case for the dtb.

**Comment by floion** [comment]
Closing as this was done via https://github.com/balena-os/balena-jetson/pull/40

**Pull request closed without merging**
