### PR TITLE
Update dtb files photon-tx2-nx to L4T R32.6.1

### PR DESCRIPTION
**Pull request by ClintHaerinck**

### CODE REVIEW

**Comment by acostach** [comment]
@ClintHaerinck thank you for your PR. For the TX2 NX on 32.6.1 you can now change the dtb binary in the dashboard, so let's keep the same default dtb - tegra186-tx2-nx-cti-NGX003-IMX219-2CAM' - for the users who already set up their boards.

**Comment by ClintHaerinck** [comment]
> @ClintHaerinck thank you for your PR. For the TX2 NX on 32.6.1 you can now change the dtb binary in the dashboard, so let's keep the same default dtb - tegra186-tx2-nx-cti-NGX003-IMX219-2CAM' - for the users who already set up their boards.

@acostach Ok, no problem. This should be ok now

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins test this please

**Review by acostach — APPROVED** [review]
lgtm

**Pull request merged**
