### PR TITLE
Aetina nx10 32.2.1

### PR DESCRIPTION
**Pull request by compiaffe**
Adding Aetina N510 and N310 carrier boards.

### CODE REVIEW

**Comment by compiaffe** [comment]
@acostach 
So I would need 3 commits, correct?
1. Yocto Machine
  - n310-tx2.conf
2. Recipe and dtbs
  - tegra186-flash-dry_32.3.1.bb
  - linux-tegra_%.bbappend
  - tegra186-tx2-aetina-n310-p3489-0888-a00-00-base.dtb
  - tegra186-tx2-aetina-n510-p3489-0888-a00-00-base.dtb
3. Coffee and icons
  - n310-tx2.coffee
  - n310-tx2.svg

**Comment by acostach** [comment]
@compiaffe It's better to have 4 commits, cause we need to have the tegra186-flash-dry changes into a different commit (it's a different package from linux-tegra)

**Comment by acostach** [comment]
@compiaffe I've added the updates trough https://github.com/balena-os/balena-jetson/pull/54 if all good on your side we can close this PR. Please let me know. Thank you!

**Comment by compiaffe** [comment]
Apologies for the late reply. All looking good on our side. We have this working on N510 and N310.

**Comment by acostach** [comment]
No worries, thanks for confirming! Closing this PR as I added the changes in another.

**Pull request closed without merging**
