### PR TITLE
Support Forecr DSBOARD-NX2

### PR DESCRIPTION
**Pull request by christopherbradski**
Hello, I am intending to add the Forecr dsboard-nx2 as a community board. Please provide assistance on how to integrate the kernel support from: https://github.com/mistelektronik/forecr_xavier_kernel for the kernel.

### CODE REVIEW

**Comment by christopherbradski** [comment]
Hello @acostach ,
Thank you for the quick response. I am using the Xavier NX in the Forecr industrial carrier board.

I am able to boot flash and boot the device after updating the files in partition 9 to contain jetson...emmc instead of the custom name and the device appears in the dashboard.

While still coming up to speed in regards to Barys and Yocto, I manually added the files from https://github.com/mistelektronik/forecr_xavier_kernel/commit/7736abaa5d4ed4765a2b05fc62f79ebc2977b314 into the kernel-source tree to try testing the industrial GPIO chip. 

Where I'm stuck is during the build it wants a response to the kernel build process:
`
| Devicetree based probing for 8250 ports (SERIAL_OF_PLATFORM) [Y/n/m/?] y
| XR17V35X PCIe UART IC driver (SERIAL_8250_XR17V35X) [M/n/y/?] (NEW) aborted!
| 
| Console input/output is redirected. Run 'make oldconfig' to update configuration.
| 
| make[3]: *** [/home/chris/src/balena-jetson/forecr-out/tmp/work-shared/forecr-dsboard-nx2/kernel-source/scripts/kconfig/Makefile:39: silentoldconfig] Error 1
| make[2]: *** [/home/chris/src/balena-jetson/forecr-out/tmp/work-shared/forecr-dsboard-nx2/kernel-source/Makefile:575: silentoldconfig] Error 2
| make[1]: Leaving directory '/home/chris/src/balena-jetson/forecr-out/tmp/work/forecr_dsboard_nx2-poky-linux/kernel-modules-headers/1.0-r0/kernel_modules_headers'
| make[1]: *** No rule to make target 'modules_prepare'.  Stop.
| make: *** [Makefile:170: sub-make] Error 2
| WARNING: exit code 2 from a shell command.
ERROR: Task (/home/chris/src/balena-jetson/forecr-out/../layers/meta-balena/meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4570 tasks of which 4532 didn't need to be rerun and 1 failed.
`
 and tried specifying "default y" but that does not seem to work.

**Comment by acostach** [comment]
Sure @christopherbradski , I'll have a look and get back to you

**Comment by acostach** [comment]
Hi @christopherbradski , I've created the device-type and added the BSP changes for this board in https://github.com/balena-os/balena-jetson/pull/503 and once the builds finish I will merge it and trigger a staging environment deploy. I'll also let you know when the staging image becomes available. If you also want to do a local build until the staging image is ready, you can use the branch in the PR.

**Comment by acostach** [comment]
Closing this old PR, feel free to re-open if necessary

**Pull request closed without merging**
