### PR TITLE
Feat/quark-nano-r32.7.1

### PR DESCRIPTION
**Pull request by ClintHaerinck**
Hi,

Is it possible to add the CTI Quark carrier board with a Jetson Nano as device type?

I saw the *.svg files are moved to another location but no idea how to add them to that submodule, possible to provide some instructions?

Kind regards,
Clint

### CODE REVIEW

**Comment by acostach** [comment]
Hi @ClintHaerinck and thank you four your PR. It seems that this carrier board can be supported trough the Nano eMMC image, so you could include the device-tree only in jetson-dtbs and then just specify the dtb to be used in the dashboard > device configuration. Can you please refactor the PR to ship the dtb only, without creating a new device type? Thanks

**Comment by ClintHaerinck** [comment]
Hi @acostach ,

Can the configuration be preloaded in the image so it's automatically set when flashing the image?

I would prefer to use the same device type as the photon-nano because it's also a CTI carrier board and CTI is doing some kernel modification (which I still need to PR). What's your opinion about this?

**Comment by acostach** [comment]
@ClintHaerinck yes, the photon-nano supports custom dtb loading - https://github.com/balena-io/open-balena-api/blob/master/src/features/vars-schema/env-vars.ts#L262 so reusing the kernel changes is fine. For the initial configuration, can you check if setting ```custom_fdt_file=my_new_custom.dtb``` in resin-boot/extra_uEnv.txt before flashing the Nano eMMC board works for you? You'll also need to plce the dtb in the rootfs, as usual, in /mnt/sysroot/active/current/boot/.

**Comment by acostach** [comment]
Closing this one for now, feel free to open a new PR that adds the dtb to the photon-nano when necessary.

**Pull request closed without merging**
