### PR TITLE
WIP: add CTI photon-nano MACHINE

### PR DESCRIPTION
**Pull request by dremsol**
@acostach I've build the image and flashed the board successfully. BalenaOS boots succesfully and quick dmesg check doesnt show any weird behaviour [dmesg.log](https://github.com/balena-os/balena-jetson/files/4511588/dmesg.log).

### CODE REVIEW

**Comment by acostach** [comment]
Thank you for your PR @dremsol. Can you please re-format it to so that it follows the standard commit guidelines? Also, please note that one of the commits has to add a "Changelog-entry".

Here's a sample PR that was adding JN30B: https://github.com/balena-os/balena-jetson/pull/26

**Comment by dremsol** [comment]
@acostach, would this align with the commit guidelines?

**Comment by acostach** [comment]
@balena-ci test this please

**Comment by floion** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@dremsol can you please re-format the last commit https://github.com/balena-os/balena-jetson/pull/60/commits/4bc6e957a56bc23fee29a77aa3e7075ea352b31b

As an example:

```
resin-image: Add Photon Nano signed device tree

Changelog-entry: photon-nano: Add photon-nano device tree
Signed-off-by: Willem Remie <w.remie@drebble.io>
```

Note that I changed the spacing between title, changelog and signed-off-by

**Comment by dremsol** [comment]
@acostach is there documentation available where i can find Balena's commit guidelines for next time?

**Comment by acostach** [comment]
@dremsol Sure, it is available in the [README](https://github.com/balena-os/balena-jetson/blob/master/README.md#pull-requests) of this repository, along with commit message examples, max lengths, etc.

**Comment by dremsol** [comment]
Well I missed that one 😅. I will do my homework next time.

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@dremsol the image is now available for download in the staging environment. Please check it out and if all is fine let me know if it should get to production.

**Comment by dremsol** [comment]
Hi @acostach, I'm not sure where to find the staging environment. Are you referring to [v2.48.0+rev4](https://github.com/balena-os/balena-jetson/commit/8ff36d03c981d289e268016ab47a89114613f08b)?

**Comment by acostach** [comment]
Hi @dremsol,

Yes, I mean checking 2.48.0+rev4 from the staging dashboard to see if it's good if it should be deployed to production dashboard.

**Comment by dremsol** [comment]
Hi @acostach, that's a welcome suprise. We were not aware of the existence of the staging environment. Wish I would know during contribution of JN30B.

Anyway, I've deployed the photon-nano and it's running a tflite model (CPU only) as GPU access is not very stable at the moment. We are pulling video from a RTSP stream and all looks good. However, i didn't test all auxiliary ports. You can take a look if you want, the device is open for support with following UUID;
`6fece44289b9260bf44992ec5c59ef9a`

As a side node; compared to stock l4t-32.3.1 CTI did minor changes to mmc drivers. Small snippet from following path `drivers/mmc/core/sd.c` they added a condition related to voltage regulator.

````c
- if (!mmc_host_is_spi(host) && rocr &&
+ 	if (!mmc_host_is_spi(host) && !host->cti_regulator_disabled && rocr &&
	   ((*rocr & 0x41000000) == 0x41000000)) {
		err = mmc_set_signal_voltage(host, MMC_SIGNAL_VOLTAGE_180,
					pocr);
````
Although I'm not in office, I've to check if kernel allows to mount an SD card without this driver change. Kernel patch should do the trick. [cti kernel source](http://connecttech.com/ftp/dropbox/cti-l4t-src-nano-32.3.1-v001.tgz)

**Pull request merged**
