### PR TITLE
Updates for 32.4.2

### PR DESCRIPTION
**Pull request by acostach**
Includes fix for https://github.com/balena-os/balena-jetson/pull/73

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci retest this please

**Comment by floion** [comment]
@balena-ci retest

**Comment by keenanjohnson** [comment]
Thanks for pushing this through all! Let me know when this should be live in the staging environment.

Cheers!

**Comment by keenanjohnson** [comment]
Hey @acostach and @floion ! I checked the balena staging environment today and I don't see a listing for the CTI Astro board yet. Is that expected?

Thanks!

**Pull request merged**
