### PR TITLE
linux-tegra: Update Nano SD basler camera dtb

### PR DESCRIPTION
**Pull request by acostach**
The current existing community basler.dtb file is actually
a compiled overlay and not a compiled device tree. Let's
apply the overlay dts from JF item
63f90f88-9bfa-44a4-8590-f78ba49bef6e on top of the sd-card
dtb and generate an the actual dtb.

Changelog-entry: linux-tegra: Update Nano SD basler camera dtb
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
Merging this as per @abrayyan confirmation in ticket https://jel.ly.fish/inbox/63f90f88-9bfa-44a4-8590-f78ba49bef6e

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
@abrayyan should we deploy this variant of the dtb in the dashboard?

**Comment by abrayyan** [comment]
@acostach I confirm this variant is working fine I tested it and would be great if you add it to the next release :)

**Pull request merged**
