### PR TITLE
WIP: JN30B L4T 32.3 BSP

### PR DESCRIPTION
**Pull request by wremie**
I've compared the BSP sources from Auvidea with stock L4T which show the majority of changes in device tree files. So replacing .dtb should do the trick here. I've not been able to flash and test the image yet due to issue in [jetson-flash](https://github.com/balena-os/jetson-flash/issues/22#issue-575238401).

during build I encountered following (non-breaking) warnings and errors;
```
NOTE: Fetching uninative binary shim from http://downloads.yoctoproject.org/releases/uninative/2.4/x86_64-nativesdk-libc.tar.bz2;sha256sum=06f91685b782f2ccfedf3070b3ba0fe4a5ba2f0766dad5c9d1642dccf95accd0
Initialising tasks: 100% |##################################################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 1341 Found 0 Missed 1341 Current 0 (0% match, 0% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: popt-native-1.16-r3 do_fetch: Failed to fetch URL http://rpm5.org/files/popt/popt-1.16.tar.gz, attempting MIRRORS if available
WARNING: swig-native-3.0.12-r0 do_fetch: Failed to fetch URL https://downloads.sourceforge.net/swig/swig-3.0.12.tar.gz, attempting MIRRORS if available
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_IP_NF_TARGET_LOG=m in the kernel configs failed for misc.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_USB_SERIAL_GENERIC=m in the kernel configs failed for usb-serial.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_CRYPTO_LZO=m in the kernel configs failed for zram.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TPROXY_IPV4=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_SOCKET_IPV4=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_TUNNEL=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_ARP=y in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_OSF=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_IPV4=y in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_FIB_NETDEV=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_SOCKET=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_SET=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_FIB_IPV6=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_NETDEV=y in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_FIB_IPV4=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_CONNLIMIT=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TPROXY_IPV6=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_INET=y in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_OBJREF=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_TPROXY=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_TABLES_IPV6=y in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_FIB=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NF_SOCKET_IPV6=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_NFT_FIB_INET=m in the kernel configs failed for nf_tables.
WARNING: linux-tegra-4.9+gitAUTOINC+47e7e1cb0b-r0 do_kernel_resin_checkconfig: Checking for CONFIG_DEBUG_KMEMLEAK_DEFAULT_OFF=y in the kernel configs failed for debug_kmemleak.
ERROR: openvpn-2.4.7-r0 do_package_qa: QA Issue: /etc/openvpn-misc/upscript.sh contained in package openvpn requires /bin/bash, but no providers found in RDEPENDS_openvpn? [file-rdeps]
ERROR: openvpn-2.4.7-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: openvpn-2.4.7-r0 do_package_qa: 
ERROR: openvpn-2.4.7-r0 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /home/willem/balena/balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/temp/log.do_package_qa.39648
ERROR: Task (/home/willem/balena/balena-jetson/build/../layers/meta-balena/meta-balena-common/recipes-connectivity/openvpn/openvpn_2.4.7.bb:do_package_qa) failed with exit code '1'
```

### CODE REVIEW

**Comment by acostach** [comment]
@wremie I'll build your PR locally and see if I can reproduce this error, but for now it seems like your build directory may be in an inconsistent state, could due to forgetting to do a `git submodule update --init --recursive' before building. I'll get back to you with my results.

**Comment by wremie** [comment]
@acostach I did start a clean barys build after submodule update, but end up with the same error. See log enclosed. 
```
git submodule status
 15f2cd4edf598ed0fee9d577a6a43cdd22a1bcb6 balena-yocto-scripts (v1.5.4)
 c6a9c9490c1ef8ef854b4afc96d4fcfae0c9928b layers/meta-balena (v2.47.1)
 6fa72d587aab8e9d56d67a2552eb9cfbe25c86d2 layers/meta-openembedded (6fa72d587)
 c5ff05d1e99c1e80844c1673456e2368499918c7 layers/meta-rust (remotes/origin/fix-debug-59-gc5ff05d)
 b391b23da57a4281968c4b25d5bf95d9cc545f50 layers/meta-tegra (krogoth-r23.2-784-gb391b23)
 f2b442c5c8e3925a4d3fc9693f1e47863dade2a9 layers/poky (warrior-21.0.0-70-gf2b442c5c8)
```
balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/temp/log.do_package_qa.90280
```
DEBUG: Executing python function sstate_task_prefunc
DEBUG: Python function sstate_task_prefunc finished
DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/home/willem/balena/balena-jetson/build/../layers/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/home/willem/balena/balena-jetson/build/../layers/poky/meta/recipes-devtools/binutils/binutils-cross_2.32.bb:do_populate_sysroot']
NOTE: Installed into sysroot: []
NOTE: Skipping as already exists in sysroot: ['pseudo-native', 'binutils-cross-aarch64', 'zlib-native', 'autoconf-native', 'texinfo-dummy-native', 'flex-native', 'gnu-config-native', 'quilt-native', 'xz-native', 'm4-native', 'gettext-minimal-native', 'automake-native', 'libtool-native']
DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Executing python function do_package_qa
NOTE: DO PACKAGE QA
DEBUG: Executing python function read_subpackage_metadata
DEBUG: Python function read_subpackage_metadata finished
NOTE: Checking Package: openvpn-locale
NOTE: Checking Package: openvpn-staticdev
NOTE: Checking Package: openvpn
NOTE: aarch64-poky-linux-objdump -p /home/willem/balena/balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/packages-split/openvpn/usr/lib/openvpn/plugins/openvpn-plugin-down-root.so
NOTE: aarch64-poky-linux-objdump -p /home/willem/balena/balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/packages-split/openvpn/usr/sbin/openvpn
ERROR: QA Issue: /etc/openvpn-misc/upscript.sh contained in package openvpn requires /bin/bash, but no providers found in RDEPENDS_openvpn? [file-rdeps]
NOTE: Checking Package: openvpn-dbg
NOTE: aarch64-poky-linux-objdump -p /home/willem/balena/balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/packages-split/openvpn-dbg/usr/lib/openvpn/plugins/.debug/openvpn-plugin-down-root.so
NOTE: aarch64-poky-linux-objdump -p /home/willem/balena/balena-jetson/build/tmp/work/aarch64-poky-linux/openvpn/2.4.7-r0/packages-split/openvpn-dbg/usr/sbin/.debug/openvpn
NOTE: Checking Package: openvpn-dev
NOTE: Checking Package: openvpn-src
NOTE: Checking Package: openvpn-doc
NOTE: Checking Package: openvpn-sample
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: 
DEBUG: Python function do_package_qa finished
ERROR: Function failed: do_package_qa
```

**Comment by acostach** [comment]
@wremie i've rebased your patches there to follow the commit guidelines in this PR: https://github.com/balena-os/balena-jetson/pull/51 so if you agree, please close the current one.

Currently I'm looking into why the LNX partitions aren't being written to the final image. It has to do with meta-tegra splitting sd and emmc nano machines in 32.3.1. I'll push the fixes there and let you know once they are ready.

**Comment by wremie** [comment]
@acostach thanks for the support. I will close this PR for now

**Pull request closed without merging**
